ALTER TABLE Student ALTER COLUMN birthday SET NOT NULL;
ALTER TABLE Mark ADD CONSTRAINT mark_range CHECK (mark >= 1 AND mark <= 10);
ALTER TABLE Subject ADD CONSTRAINT grade_range CHECK (GRADE >= 1 AND GRADE <= 5);
ALTER TABLE PAYMENTTYPE ADD CONSTRAINT name UNIQUE (NAME);
ALTER TABLE PAYMENT ALTER COLUMN TYPE_ID  SET NOT NULL;
ALTER TABLE PAYMENT ALTER COLUMN AMOUNT SET NOT NULL;
ALTER TABLE PAYMENT ALTER COLUMN payment_date SET NOT NULL;