DELETE FROM Student WHERE GROUPNUMBER > 4;
DELETE FROM Student WHERE id IN (SELECT MARK.student_id FROM MARK WHERE mark < 4);
DELETE FROM PAYMENTTYPE WHERE id = 1;
DELETE FROM MARK WHERE mark < 7;
