SELECT birthday FROM STUDENT ORDER BY birthday desc LIMIT 1;
SELECT payment_date FROM PAYMENT ORDER BY payment_date LIMIT 1;
SELECT AVG(CAST(mark AS DECIMAL(10,2))) FROM MARK WHERE SUBJECT_ID = 104;
SELECT MIN(AMOUNT) FROM PAYMENT WHERE type_id = 002;