SELECT * FROM PAYMENT WHERE amount >= 500;
SELECT * FROM Student WHERE DATEDIFF(YEAR, birthday, CURRENT_DATE) > 20;
SELECT * FROM STUDENT WHERE "group" = 10 AND DATEDIFF(YEAR, birthday, CURRENT_DATE) < 20;
SELECT * FROM STUDENT WHERE NAME = 'Mike' OR "group" = 4 OR "group" = 5 OR "group" = 6;
SELECT * FROM PAYMENT WHERE DATEDIFF(MONTH , payment_date, CURRENT_DATE) < 8;
SELECT * FROM STUDENT WHERE NAME LIKE 'A%';
SELECT * FROM STUDENT WHERE (name = 'Roxi' AND "group" = 4) OR (name = 'Tallie' AND "group" = 9);