SELECT * FROM PAYMENT WHERE TYPE_ID = 001;
SELECT * FROM MARK WHERE name = 'Art';
SELECT s.* FROM Student s INNER JOIN PAYMENT P2 on s.ID = P2.STUDENT_ID WHERE P2.TYPE_ID=002;
SELECT s1.* FROM Student s1 JOIN Mark M on s1.id = M.student_id WHERE m.SUBJECT_ID= 0006;